### ISSUE TITLE
Error after update Toolkit to v13.0.0-rc20

### ISSUE THREAD

**Issue by ronaldoguedess** [zeta-chain/toolkit#288]
Error on `hardhat.config` after updating Toolkit to: `v13.0.0-rc20`, returning to `v13.0.0-rc19` solve issue!

![Image](https://github.com/user-attachments/assets/a6cbd719-288f-403e-8da0-c096b1111a15)

Is it an issue or is there something that I need to include on the `hardhat.config`?

**Comment by fadeev** [comment]
@ronaldoguedess thanks for reporting this! Some functions including `getHardhatConfig` have been moved into the utils directory, but `utils` hasn't been exported. https://github.com/zeta-chain/toolkit/pull/289 should fix it. cc @hernan-clich

**Comment by ronaldoguedess** [comment]
@fadeev it do not fix the issue.... 

 I had the: toolkit@13.0.0-rc19

I updated with this:
`npm install @zetachain/toolkit@13.0.0`

And this is the issue:
```
PS C:\Users\ronaldo\test65\example-contracts\examples\swap> npx hardhat compile 
An unexpected error occurred:

TypeError: (0 , client_1.getHardhatConfig) is not a function
    at Object.<anonymous> (C:\Users\ronaldo\test65\example-contracts\examples\swap\hardhat.config.ts:16:22)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module.m._compile (C:\Users\ronaldo\test65\example-contracts\examples\swap\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\ronaldo\test65\example-contracts\examples\swap\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at importCsjOrEsModule (C:\Users\ronaldo\test65\example-contracts\examples\swap\node_modules\hardhat\src\internal\core\config\config-loading.ts:29:22)
PS C:\Users\ronaldo\test65\example-contracts\examples\swap>
```

**Comment by ronaldoguedess** [comment]
can you show your `hardhat.config`

This is my one:
```
import "@nomicfoundation/hardhat-toolbox";
import { HardhatUserConfig } from "hardhat/config";
import * as dotenv from "dotenv";

import "./tasks";
import "@zetachain/localnet/tasks";
import "@zetachain/toolkit/tasks";

import { getHardhatConfig } from "@zetachain/toolkit/client";

import "@openzeppelin/hardhat-upgrades";

dotenv.config();

const config: HardhatUserConfig = {
  ...getHardhatConfig({ accounts: [process.env.PRIVATE_KEY] }), // mantém tudo da Zeta
  solidity: {
    compilers: [
      {
        version: "0.8.26", // usa viaIR aqui
        settings: {
          optimizer: {
            enabled: true,
            runs: 999999,
          },
          viaIR: true,
        },
      },
      // os outros ficam normais
      { version: "0.8.7" },
      { version: "0.8.5" },
      { version: "0.8.9" },
      { version: "0.5.16" },
      { version: "0.6.6" },
      { version: "0.4.18" },
      { version: "0.8.20" },
    ],
  },
};

export default config;

```

**Comment by fadeev** [comment]
It has been moved to utils:

```ts
import { getHardhatConfig } from "@zetachain/toolkit/utils";
```
